name: DGFit

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - sphinx-astropy
#   - pip:
#       - dependency_from_pip
